# Generated by Django 5.2.8 on 2025-11-28 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_alter_email_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
