# Generated by Django 5.2.8 on 2025-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0005_alter_email_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
