# Generated by Django 5.2.8 on 2025-12-05 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0008_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
