# Generated by Django 5.2.8 on 2025-12-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0009_chatmessage_starred_by'),
        ('django_backend', '0009_task'),
    ]

    operations = [
    ]
