# Generated by Django 5.2.8 on 2025-12-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0010_merge_0009_chatmessage_starred_by_0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
