# Generated by Django 5.2.8 on 2025-12-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0011_chatmessage_is_deleted'),
        ('django_backend', '0011_email_is_spam'),
    ]

    operations = [
    ]
