# Generated by Django 5.2.8 on 2025-12-08 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0012_merge_0011_chatmessage_is_deleted_0011_email_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
