# Generated by Django 5.2.8 on 2025-12-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0013_chatmessage_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
