# Generated by Django 5.2.8 on 2025-12-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0014_email_is_read'),
        ('django_backend', '0014_userprofile'),
    ]

    operations = [
    ]
