# Generated by Django 5.2.8 on 2025-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0016_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store_activity',
            field=models.BooleanField(default=True),
        ),
    ]
