# Generated by Django 5.2.8 on 2025-12-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0019_meeting'),
        ('django_backend', '0019_note'),
    ]

    operations = [
    ]
