# Generated by Django 5.2.8 on 2025-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0020_merge_0019_meeting_0019_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='call_type',
            field=models.CharField(choices=[('audio', 'Audio Call'), ('video', 'Video Call'), ('group', 'Group Call')], default='video', max_length=10),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
