# Generated by Django 5.2.8 on 2025-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0021_event_eventattendee_eventreminder_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Government Holiday',
                'verbose_name_plural': 'Government Holidays',
                'ordering': ['date'],
            },
        ),
    ]
