# Generated by Django 5.2.8 on 2025-12-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0021_meeting_call_type_delete_note'),
        ('django_backend', '0023_note'),
    ]

    operations = [
    ]
