# Generated by Django 5.2.8 on 2025-12-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0022_notification'),
        ('django_backend', '0024_merge_0021_meeting_call_type_delete_note_0023_note'),
    ]

    operations = [
    ]
