# Generated by Django 5.2.8 on 2025-12-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0026_remove_user_is_staff_remove_user_nationality_and_more'),
        ('django_backend', '0026_task_assigned_to_task_due_date_task_priority_and_more'),
    ]

    operations = [
    ]
