# Generated by Django 5.2.8 on 2025-12-23 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0031_note_project_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recovery_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        
    ]
