# Generated by Django 5.2.8 on 2025-12-19 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0031_note_project_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='django_backend.chatmessage'),
        ),
    
    ]
