# Generated by Django 5.2.8 on 2025-12-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0032_remove_user_recovery_email_remove_user_surname_note'),
        ('django_backend', '0034_chatmessage_is_forwarded_note'),
    ]

    operations = [
    ]
