# Generated by Django 5.2.8 on 2025-12-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0036_user_last_seen_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_MEETING', 'In Meeting'), ('DND', 'Do Not Disturb'), ('BRB', 'Be Right Back'), ('AWAY', 'Appear Away'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manually_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        
    ]
