# Generated by Django 5.2.8 on 2025-12-29 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0037_user_current_status_user_is_manually_set_and_more'),
    ]

    operations = [
       
    ]
